import type { Block } from 'payload'

export const AboutTextSlider: Block = {
  slug: 'aboutTextSlider',
  interfaceName: 'AboutTextSliderBlock',
  labels: { singular: 'About - Text and Slider', plural: 'About - Text and Slider' },
  fields: [
    {
      name: 'heading',
      label: 'Heading',
      type: 'text',
      required: true,
    },
    {
      name: 'accentWord',
      label: 'Heading Accent',
      type: 'text',
      admin: {
        description: 'Exact word in the heading to accent (case-insensitive).',
      },
    },
    {
      name: 'content',
      label: 'Text',
      type: 'richText',
    },
    {
      name: 'slides',
      type: 'array',
      labels: { singular: 'Slide', plural: 'Slides' },
      minRows: 1,
      fields: [
        {
          name: 'icon',
          type: 'select',
          label: 'Google Icon (Material Symbols)',
          required: true,
          defaultValue: 'restaurant',
          options: [
            { label: 'Cooking', value: 'restaurant' },
            { label: 'Nutrition', value: 'nutrition' },
            { label: 'Home', value: 'home' },
            { label: 'Egg', value: 'egg_alt' },
            { label: 'Pet supplies', value: 'pet_supplies' },
            { label: 'Activism', value: 'volunteer_activism' },
            { label: 'Health Cross', value: 'health_cross' },
            { label: 'Scale', value: 'scale' },
            { label: 'Shield', value: 'shield' },
            { label: 'Calendar', value: 'calendar_today' },
            { label: 'Sunny', value: 'sunny' },
            { label: 'Bolt', value: 'bolt' },
            { label: 'Water', value: 'water' },
            { label: 'Pill', value: 'pill' },
            { label: 'Dog', value: 'sound_detection_dog_barking' },
            { label: 'Paw', value: 'pets' },
            { label: 'Skillet', value: 'skillet' },
            { label: 'Grain', value: 'grain' },
            { label: 'Family Home', value: 'family_home' },
            { label: 'Meat', value: 'meat_icon' },
            { label: 'Favorite', value: 'favorite' },
            { label: 'Neurology', value: 'neurology' },
            { label: 'Mood', value: 'mood' },
            { label: 'Dentistry', value: 'dentistry' },
            { label: 'Rheumatology', value: 'rheumatology' },
            { label: 'Error', value: 'error' },
            { label: 'Health and Safety', value: 'health_and_safety' },
            { label: 'Gastroenterology', value: 'gastroenterology' },
            { label: 'Balance', value: 'balance' },
            { label: 'Pest Control', value: 'pest_control' },
            { label: 'Scissor', value: 'content_cut' },
            { label: 'Vital Signs', value: 'vital_signs' },
            { label: 'Syringe', value: 'syringe' },
          ],
          admin: {
            description: 'Uses Material Symbols Outlined; type name is rendered as icon.',
          },
        },
        {
          name: 'title',
          type: 'text',
          label: 'Title',
          required: true,
        },
        {
          name: 'paragraph',
          type: 'textarea',
          label: 'Paragraph',
          required: true,
        },
      ],
    },
  ],
}