import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_food_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum_food_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_food_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__food_v_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum__food_v_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__food_v_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_recipes_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum_recipes_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_recipes_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__recipes_v_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum__recipes_v_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__recipes_v_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_health_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum_health_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_health_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__health_v_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum__health_v_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__health_v_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_sub_hubs_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum_sub_hubs_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum_sub_hubs_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__sub_hubs_v_blocks_tabs_container_size" AS ENUM('container', 'container-small');
  CREATE TYPE "public"."enum__sub_hubs_v_blocks_tabs_tabs_gap" AS ENUM('default', 'small');
  CREATE TYPE "public"."enum__sub_hubs_v_blocks_tabs_tabs_padding" AS ENUM('default', 'small');
  ALTER TABLE "food_blocks_tabs" ADD COLUMN "container_size" "enum_food_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "food_blocks_tabs" ADD COLUMN "tabs_gap" "enum_food_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "food_blocks_tabs" ADD COLUMN "tabs_padding" "enum_food_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "_food_v_blocks_tabs" ADD COLUMN "container_size" "enum__food_v_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "_food_v_blocks_tabs" ADD COLUMN "tabs_gap" "enum__food_v_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "_food_v_blocks_tabs" ADD COLUMN "tabs_padding" "enum__food_v_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "recipes_blocks_tabs" ADD COLUMN "container_size" "enum_recipes_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "recipes_blocks_tabs" ADD COLUMN "tabs_gap" "enum_recipes_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "recipes_blocks_tabs" ADD COLUMN "tabs_padding" "enum_recipes_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "_recipes_v_blocks_tabs" ADD COLUMN "container_size" "enum__recipes_v_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "_recipes_v_blocks_tabs" ADD COLUMN "tabs_gap" "enum__recipes_v_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "_recipes_v_blocks_tabs" ADD COLUMN "tabs_padding" "enum__recipes_v_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "health_blocks_tabs" ADD COLUMN "container_size" "enum_health_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "health_blocks_tabs" ADD COLUMN "tabs_gap" "enum_health_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "health_blocks_tabs" ADD COLUMN "tabs_padding" "enum_health_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "_health_v_blocks_tabs" ADD COLUMN "container_size" "enum__health_v_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "_health_v_blocks_tabs" ADD COLUMN "tabs_gap" "enum__health_v_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "_health_v_blocks_tabs" ADD COLUMN "tabs_padding" "enum__health_v_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "sub_hubs_blocks_tabs" ADD COLUMN "container_size" "enum_sub_hubs_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "sub_hubs_blocks_tabs" ADD COLUMN "tabs_gap" "enum_sub_hubs_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "sub_hubs_blocks_tabs" ADD COLUMN "tabs_padding" "enum_sub_hubs_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "_sub_hubs_v_blocks_tabs" ADD COLUMN "container_size" "enum__sub_hubs_v_blocks_tabs_container_size" DEFAULT 'container';
  ALTER TABLE "_sub_hubs_v_blocks_tabs" ADD COLUMN "tabs_gap" "enum__sub_hubs_v_blocks_tabs_tabs_gap" DEFAULT 'default';
  ALTER TABLE "_sub_hubs_v_blocks_tabs" ADD COLUMN "tabs_padding" "enum__sub_hubs_v_blocks_tabs_tabs_padding" DEFAULT 'default';
  ALTER TABLE "food_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "food_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "_food_v_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "_food_v_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "recipes_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "recipes_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "_recipes_v_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "_recipes_v_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "health_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "health_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "_health_v_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "_health_v_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "sub_hubs_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "sub_hubs_blocks_tabs" DROP COLUMN "desktop_padding";
  ALTER TABLE "_sub_hubs_v_blocks_tabs" DROP COLUMN "desktop_gap";
  ALTER TABLE "_sub_hubs_v_blocks_tabs" DROP COLUMN "desktop_padding";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "food_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "food_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "_food_v_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "_food_v_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "recipes_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "recipes_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "_recipes_v_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "_recipes_v_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "health_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "health_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "_health_v_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "_health_v_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "sub_hubs_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "sub_hubs_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "_sub_hubs_v_blocks_tabs" ADD COLUMN "desktop_gap" varchar DEFAULT '23px';
  ALTER TABLE "_sub_hubs_v_blocks_tabs" ADD COLUMN "desktop_padding" varchar DEFAULT '57px';
  ALTER TABLE "food_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "food_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "food_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "_food_v_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "_food_v_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "_food_v_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "recipes_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "recipes_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "recipes_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "_recipes_v_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "_recipes_v_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "_recipes_v_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "health_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "health_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "health_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "_health_v_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "_health_v_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "_health_v_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "sub_hubs_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "sub_hubs_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "sub_hubs_blocks_tabs" DROP COLUMN "tabs_padding";
  ALTER TABLE "_sub_hubs_v_blocks_tabs" DROP COLUMN "container_size";
  ALTER TABLE "_sub_hubs_v_blocks_tabs" DROP COLUMN "tabs_gap";
  ALTER TABLE "_sub_hubs_v_blocks_tabs" DROP COLUMN "tabs_padding";
  DROP TYPE "public"."enum_food_blocks_tabs_container_size";
  DROP TYPE "public"."enum_food_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum_food_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum__food_v_blocks_tabs_container_size";
  DROP TYPE "public"."enum__food_v_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum__food_v_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum_recipes_blocks_tabs_container_size";
  DROP TYPE "public"."enum_recipes_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum_recipes_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum__recipes_v_blocks_tabs_container_size";
  DROP TYPE "public"."enum__recipes_v_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum__recipes_v_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum_health_blocks_tabs_container_size";
  DROP TYPE "public"."enum_health_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum_health_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum__health_v_blocks_tabs_container_size";
  DROP TYPE "public"."enum__health_v_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum__health_v_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum_sub_hubs_blocks_tabs_container_size";
  DROP TYPE "public"."enum_sub_hubs_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum_sub_hubs_blocks_tabs_tabs_padding";
  DROP TYPE "public"."enum__sub_hubs_v_blocks_tabs_container_size";
  DROP TYPE "public"."enum__sub_hubs_v_blocks_tabs_tabs_gap";
  DROP TYPE "public"."enum__sub_hubs_v_blocks_tabs_tabs_padding";`)
}
