/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    workshops: Workshop;
    media: Media;
    categories: Category;
    users: User;
    authors: Author;
    food: Food;
    recipes: Recipe;
    howTo: HowTo;
    health: Health;
    subHubs: SubHub;
    hubs: Hub;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    workshops: WorkshopsSelect<false> | WorkshopsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    food: FoodSelect<false> | FoodSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    howTo: HowToSelect<false> | HowToSelect<true>;
    health: HealthSelect<false> | HealthSelect<true>;
    subHubs: SubHubsSelect<false> | SubHubsSelect<true>;
    hubs: HubsSelect<false> | HubsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    popup: Popup;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    popup: PopupSelect<false> | PopupSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  locked?: boolean | null;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | {
        heading: string;
        placeholder?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'searchLayout';
      }
    | {
        heading: string;
        populateBy: 'recent' | 'manual';
        /**
         * Pick exactly two recipes (posts).
         */
        items?:
          | {
              reference: {
                relationTo: 'posts';
                value: number | Post;
              };
              id?: string | null;
            }[]
          | null;
        usePlaceholders?: boolean | null;
        placeholderText?: string | null;
        placeholderImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'onboardingChecklist';
      }
    | FeaturedBlock
    | ToggledCollectionsBlock
    | RecentWorkshopsBlock
    | AboutHeroBlock
    | AboutTextImageBlock
    | AboutBannerBlock
    | AboutTextSliderBlock
    | ContactHeroBlock
    | ContactInfoBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  locked?: boolean | null;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedBlock".
 */
export interface FeaturedBlock {
  heading: string;
  items?:
    | {
        item:
          | {
              relationTo: 'posts';
              value: number | Post;
            }
          | {
              relationTo: 'workshops';
              value: number | Workshop;
            }
          | {
              relationTo: 'food';
              value: number | Food;
            }
          | {
              relationTo: 'howTo';
              value: number | HowTo;
            }
          | {
              relationTo: 'health';
              value: number | Health;
            };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featured';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops".
 */
export interface Workshop {
  id: number;
  locked?: boolean | null;
  title: string;
  watch_time?: string | null;
  layout?: (VideoHeroBlock | AuthorBlock)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories?: (number | Category)[] | null;
  /**
   * e.g., "2hr 30m", "45 minutes", "1h 15m"
   */
  totalWatchTime?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoHeroBlock".
 */
export interface VideoHeroBlock {
  containerSize: 'container' | 'container-small';
  videoUrl: string;
  thumbnail: number | Media;
  tag?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'VideoHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthorBlock".
 */
export interface AuthorBlock {
  containerSize: 'container' | 'container-small';
  displayMode: 'default' | 'recipe';
  author: number | Author;
  id?: string | null;
  blockName?: string | null;
  blockType: 'author';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  image?: (number | null) | Media;
  name: string;
  author_title?: string | null;
  certifications?:
    | {
        name: string;
        type: 'url' | 'file';
        url?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food".
 */
export interface Food {
  id: number;
  locked?: boolean | null;
  image?: (number | null) | Media;
  name: string;
  subHubs?: (number | SubHub)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | Category)[] | null;
  layout?: (SinglePageHeroBlock | TabsBlock | ReferencesBlock | ContentBlock1)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subHubs".
 */
export interface SubHub {
  id: number;
  locked?: boolean | null;
  title: string;
  /**
   * Which collection this sub-hub belongs to
   */
  collection: 'health' | 'food' | 'howTo' | 'recipes';
  publishedAt?: string | null;
  /**
   * Relates this Sub Hub to its parent Hub
   */
  hub?: (number | null) | Hub;
  layout: (SinglePageHeroBlock | TabsBlock | HealthSectionsBlock | ContentBlock1 | CallToActionBlock | MediaBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs".
 */
export interface Hub {
  id: number;
  locked?: boolean | null;
  title: string;
  subHubs?: (number | SubHub)[] | null;
  layout: (
    | HubHeroBlock
    | TabsBlock
    | ContentBlock1
    | IconSliderBlock
    | SliderBlock
    | TestimonialBlock
    | FeaturedWorkshopBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubHeroBlock".
 */
export interface HubHeroBlock {
  containerSize: 'container' | 'container-small';
  /**
   * Examples: #41A690, rgb(65,166,144), teal
   */
  backgroundColor: string;
  heading: string;
  subheading?: string | null;
  searchPlaceholder?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hubHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock".
 */
export interface TabsBlock {
  containerSize: 'container' | 'container-small';
  tabsGap: 'default' | 'small';
  tabsPadding: 'default' | 'small';
  tabs?:
    | {
        title: string;
        anchor: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentBlock".
 */
export interface ContentBlock1 {
  containerSize: 'container' | 'container-small';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconSliderBlock".
 */
export interface IconSliderBlock {
  title: string;
  title_mobile?: string | null;
  boxes: {
    /**
     * Uses Material Symbols Outlined; type name is rendered as icon.
     */
    icon:
      | 'restaurant'
      | 'nutrition'
      | 'home'
      | 'egg_alt'
      | 'pet_supplies'
      | 'volunteer_activism'
      | 'health_cross'
      | 'scale'
      | 'shield'
      | 'calendar_today'
      | 'sunny'
      | 'bolt'
      | 'water'
      | 'pill'
      | 'sound_detection_dog_barking'
      | 'pets'
      | 'skillet'
      | 'grain'
      | 'family_home'
      | 'meat_icon'
      | 'favorite'
      | 'neurology'
      | 'mood'
      | 'dentistry'
      | 'rheumatology'
      | 'error'
      | 'health_and_safety'
      | 'gastroenterology'
      | 'balance'
      | 'pest_control'
      | 'content_cut'
      | 'vital_signs'
      | 'syringe';
    title: string;
    /**
     * Link to navigate when tapped.
     */
    url?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlock".
 */
export interface SliderBlock {
  containerSize: 'container' | 'container-small';
  title?: string | null;
  aspectRatio?:
    | (
        | 'aspect-[1/1]'
        | 'aspect-[4/5]'
        | 'aspect-[3/4]'
        | 'aspect-[16/9]'
        | 'aspect-[251/150]'
        | 'aspect-[116/75]'
        | 'aspect-[116:75]'
      )
    | null;
  centerSlidesOnMobile?: boolean | null;
  overflowSetting?: ('overflow-hidden' | 'overflow-visible' | 'overflow-hidden md:overflow-visible') | null;
  desktopSlidesPerView: '3' | '4' | '5' | '6';
  items?:
    | {
        reference:
          | {
              relationTo: 'health';
              value: number | Health;
            }
          | {
              relationTo: 'workshops';
              value: number | Workshop;
            }
          | {
              relationTo: 'recipes';
              value: number | Recipe;
            }
          | {
              relationTo: 'howTo';
              value: number | HowTo;
            }
          | {
              relationTo: 'food';
              value: number | Food;
            };
        id?: string | null;
      }[]
    | null;
  usePlaceholders?: boolean | null;
  placeholderImage?: (number | null) | Media;
  placeholderTitle?: string | null;
  placeholderCount?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health".
 */
export interface Health {
  id: number;
  locked?: boolean | null;
  title: string;
  subHubs?: (number | SubHub)[] | null;
  layout: (SinglePageHeroBlock | TabsBlock | HealthSectionsBlock | ContentBlock1)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SinglePageHeroBlock".
 */
export interface SinglePageHeroBlock {
  containerSize: 'container' | 'container-small';
  orientation: 'horizontal' | 'vertical';
  image?: (number | null) | Media;
  title?: string | null;
  enableAuthor?: boolean | null;
  authors?: (number | Author)[] | null;
  heading?: string | null;
  paragraph?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'singlePageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HealthSectionsBlock".
 */
export interface HealthSectionsBlock {
  sections?:
    | {
        type: 'richText' | 'accordion' | 'table' | 'content';
        heading: string;
        /**
         * Used as the section ID (e.g. description). Tabs can link to #description.
         */
        anchor?: string | null;
        tableOverflow: 'default' | 'overflow';
        tableIntro?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        columns?:
          | {
              title: string;
              columnType: 'text' | 'input';
              inputType?: ('checkbox' | 'text' | 'number' | 'textarea') | null;
              id?: string | null;
            }[]
          | null;
        tableRows?:
          | {
              /**
               * Enter texts for text-type columns in order. Input columns do not need values.
               */
              cells?:
                | {
                    text?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        topContent?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableImportant?: boolean | null;
        importantTitle?: string | null;
        importantText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        contentRows?:
          | {
              leftHeading: string;
              rightText: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        bottomContent?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        accordionIntro?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items?:
          | {
              title: string;
              subtitle?: string | null;
              icon?: ('paw' | 'leaf' | 'sparkles' | 'medkit' | 'activity') | null;
              content: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'healthSections';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  locked?: boolean | null;
  image?: (number | null) | Media;
  name: string;
  subHubs?: (number | SubHub)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | Category)[] | null;
  layout?:
    | (
        | RecipeHeroBlock
        | SinglePageHeroBlock
        | TabsBlock
        | ReferencesBlock
        | ContentBlock1
        | TabbedContentBlock
        | AuthorBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecipeHeroBlock".
 */
export interface RecipeHeroBlock {
  containerSize: 'container' | 'container-small';
  image: number | Media;
  heading: string;
  whoIsThisFor: {
    text: string;
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'recipeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReferencesBlock".
 */
export interface ReferencesBlock {
  containerSize: 'container' | 'container-small';
  title: string;
  /**
   * Constrains the content to max-width of 1219px and centers it while keeping border full width
   */
  widthConstraint?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'References';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock".
 */
export interface TabbedContentBlock {
  containerSize: 'container' | 'container-small';
  /**
   * Background color for the tabbed content container (e.g., #f8f9fa, rgba(248, 249, 250, 1))
   */
  backgroundColor?: string | null;
  /**
   * Color for inactive tabs (e.g., #6c757d, rgba(108, 117, 125, 1))
   */
  inactiveTabColor?: string | null;
  /**
   * Border color for tabs and content area (e.g., #dee2e6, rgba(222, 226, 230, 1))
   */
  borderColor?: string | null;
  tabs?:
    | {
        title: string;
        enableScale?: boolean | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "howTo".
 */
export interface HowTo {
  id: number;
  locked?: boolean | null;
  title: string;
  layout: (
    | SinglePageHeroBlock
    | {
        containerSize: 'container' | 'container-small';
        resources?:
          | {
              image?: (number | null) | Media;
              title: string;
              linkType: 'url' | 'file';
              url?: string | null;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        steps?:
          | {
              heading: string;
              swapColumns?: boolean | null;
              image?: (number | null) | Media;
              mobile_image?: (number | null) | Media;
              columnsProportion: '6-6' | '7-5';
              /**
               * Maximum width for the Pro tip / Important box.
               */
              tipMaxWidthPx?: number | null;
              useContentRepeater?: boolean | null;
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              contentRows?:
                | {
                    title: string;
                    paragraph?: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    id?: string | null;
                  }[]
                | null;
              tooltipEnabled?: boolean | null;
              tooltipVariant?: ('proTip' | 'important') | null;
              tooltipText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              /**
               * Adds 3.5rem padding-left to bullet lists on desktop
               */
              useListIndentation?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'howToSections';
      }
    | {
        containerSize: 'container' | 'container-small';
        heading: string;
        list?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        disclosure?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'howToInformation';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  containerSize: 'container' | 'container-small';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | Author;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWorkshopBlock".
 */
export interface FeaturedWorkshopBlock {
  label?: string | null;
  containerSize: 'container' | 'container-small';
  workshop: number | Workshop;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredWorkshop';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToggledCollectionsBlock".
 */
export interface ToggledCollectionsBlock {
  collections?:
    | {
        collection: 'food' | 'health' | 'howTo';
        itemCount: number;
        /**
         * Duplicate items to fill the specified count if there are not enough items
         */
        fillContent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'toggledCollections';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentWorkshopsBlock".
 */
export interface RecentWorkshopsBlock {
  /**
   * Heading text for the section
   */
  heading?: string | null;
  /**
   * Fill remaining slots with repeated workshops if less than 3 are available
   */
  repeat?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recentWorkshops';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock".
 */
export interface AboutHeroBlock {
  heading: string;
  /**
   * Exact word in the heading to accent (case-insensitive).
   */
  accentWord?: string | null;
  imageLeft: number | Media;
  imageCenter: number | Media;
  imageRight: number | Media;
  showArrow?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTextImageBlock".
 */
export interface AboutTextImageBlock {
  heading: string;
  /**
   * Exact word in the heading to accent (case-insensitive).
   */
  accentWord?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  imageTop: number | Media;
  imageCenter: number | Media;
  imageBottom: number | Media;
  showSparkle?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutTextImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBannerBlock".
 */
export interface AboutBannerBlock {
  heading: string;
  subheading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTextSliderBlock".
 */
export interface AboutTextSliderBlock {
  heading: string;
  /**
   * Exact word in the heading to accent (case-insensitive).
   */
  accentWord?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slides?:
    | {
        /**
         * Uses Material Symbols Outlined; type name is rendered as icon.
         */
        icon:
          | 'restaurant'
          | 'nutrition'
          | 'home'
          | 'egg_alt'
          | 'pet_supplies'
          | 'volunteer_activism'
          | 'health_cross'
          | 'scale'
          | 'shield'
          | 'calendar_today'
          | 'sunny'
          | 'bolt'
          | 'water'
          | 'pill'
          | 'sound_detection_dog_barking'
          | 'pets'
          | 'skillet'
          | 'grain'
          | 'family_home'
          | 'meat_icon'
          | 'favorite'
          | 'neurology'
          | 'mood'
          | 'dentistry'
          | 'rheumatology'
          | 'error'
          | 'health_and_safety'
          | 'gastroenterology'
          | 'balance'
          | 'pest_control'
          | 'content_cut'
          | 'vital_signs'
          | 'syringe';
        title: string;
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutTextSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactHeroBlock".
 */
export interface ContactHeroBlock {
  /**
   * Main heading text (e.g., "tell your dog we say hi!")
   */
  heading: string;
  /**
   * Word to highlight in coral color (e.g., "hi"). Case-insensitive match.
   */
  accentWord?: string | null;
  /**
   * Text displayed below the heading
   */
  description: string;
  /**
   * Dog photo displayed on the right side (desktop) or top (mobile)
   */
  dogImage: number | Media;
  /**
   * Small decorative graphic displayed next to the heading
   */
  decorativeIcon?: (number | null) | Media;
  namePlaceholder?: string | null;
  emailPlaceholder?: string | null;
  messagePlaceholder?: string | null;
  /**
   * Text displayed on the submit button
   */
  submitButtonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  /**
   * Main heading text for the contact info section
   */
  heading: string;
  /**
   * Text displayed below the heading
   */
  description: string;
  emailPlaceholder?: string | null;
  /**
   * Text displayed on the submit button
   */
  submitButtonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'food';
        value: number | Food;
      }
    | {
        relationTo: 'health';
        value: number | Health;
      }
    | {
        relationTo: 'howTo';
        value: number | HowTo;
      }
    | {
        relationTo: 'workshops';
        value: number | Workshop;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  locked?: boolean | null;
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'workshops';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'food';
        value: number | Food;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'howTo';
        value: number | HowTo;
      } | null)
    | ({
        relationTo: 'health';
        value: number | Health;
      } | null)
    | ({
        relationTo: 'subHubs';
        value: number | SubHub;
      } | null)
    | ({
        relationTo: 'hubs';
        value: number | Hub;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        searchLayout?:
          | T
          | {
              heading?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        onboardingChecklist?:
          | T
          | {
              heading?: T;
              populateBy?: T;
              items?:
                | T
                | {
                    reference?: T;
                    id?: T;
                  };
              usePlaceholders?: T;
              placeholderText?: T;
              placeholderImage?: T;
              id?: T;
              blockName?: T;
            };
        featured?: T | FeaturedBlockSelect<T>;
        toggledCollections?: T | ToggledCollectionsBlockSelect<T>;
        recentWorkshops?: T | RecentWorkshopsBlockSelect<T>;
        aboutHero?: T | AboutHeroBlockSelect<T>;
        aboutTextImage?: T | AboutTextImageBlockSelect<T>;
        aboutBanner?: T | AboutBannerBlockSelect<T>;
        aboutTextSlider?: T | AboutTextSliderBlockSelect<T>;
        contactHero?: T | ContactHeroBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedBlock_select".
 */
export interface FeaturedBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        item?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToggledCollectionsBlock_select".
 */
export interface ToggledCollectionsBlockSelect<T extends boolean = true> {
  collections?:
    | T
    | {
        collection?: T;
        itemCount?: T;
        fillContent?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentWorkshopsBlock_select".
 */
export interface RecentWorkshopsBlockSelect<T extends boolean = true> {
  heading?: T;
  repeat?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock_select".
 */
export interface AboutHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  accentWord?: T;
  imageLeft?: T;
  imageCenter?: T;
  imageRight?: T;
  showArrow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTextImageBlock_select".
 */
export interface AboutTextImageBlockSelect<T extends boolean = true> {
  heading?: T;
  accentWord?: T;
  content?: T;
  imageTop?: T;
  imageCenter?: T;
  imageBottom?: T;
  showSparkle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBannerBlock_select".
 */
export interface AboutBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTextSliderBlock_select".
 */
export interface AboutTextSliderBlockSelect<T extends boolean = true> {
  heading?: T;
  accentWord?: T;
  content?: T;
  slides?:
    | T
    | {
        icon?: T;
        title?: T;
        paragraph?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactHeroBlock_select".
 */
export interface ContactHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  accentWord?: T;
  description?: T;
  dogImage?: T;
  decorativeIcon?: T;
  namePlaceholder?: T;
  emailPlaceholder?: T;
  messagePlaceholder?: T;
  submitButtonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  emailPlaceholder?: T;
  submitButtonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops_select".
 */
export interface WorkshopsSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  watch_time?: T;
  layout?:
    | T
    | {
        VideoHero?: T | VideoHeroBlockSelect<T>;
        author?: T | AuthorBlockSelect<T>;
      };
  content?: T;
  categories?: T;
  totalWatchTime?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoHeroBlock_select".
 */
export interface VideoHeroBlockSelect<T extends boolean = true> {
  containerSize?: T;
  videoUrl?: T;
  thumbnail?: T;
  tag?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthorBlock_select".
 */
export interface AuthorBlockSelect<T extends boolean = true> {
  containerSize?: T;
  displayMode?: T;
  author?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  image?: T;
  name?: T;
  author_title?: T;
  certifications?:
    | T
    | {
        name?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_select".
 */
export interface FoodSelect<T extends boolean = true> {
  locked?: T;
  image?: T;
  name?: T;
  subHubs?: T;
  description?: T;
  categories?: T;
  layout?:
    | T
    | {
        singlePageHero?: T | SinglePageHeroBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        References?: T | ReferencesBlockSelect<T>;
        contentBlock?: T | ContentBlockSelect1<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SinglePageHeroBlock_select".
 */
export interface SinglePageHeroBlockSelect<T extends boolean = true> {
  containerSize?: T;
  orientation?: T;
  image?: T;
  title?: T;
  enableAuthor?: T;
  authors?: T;
  heading?: T;
  paragraph?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock_select".
 */
export interface TabsBlockSelect<T extends boolean = true> {
  containerSize?: T;
  tabsGap?: T;
  tabsPadding?: T;
  tabs?:
    | T
    | {
        title?: T;
        anchor?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReferencesBlock_select".
 */
export interface ReferencesBlockSelect<T extends boolean = true> {
  containerSize?: T;
  title?: T;
  widthConstraint?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentBlock_select".
 */
export interface ContentBlockSelect1<T extends boolean = true> {
  containerSize?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  locked?: T;
  image?: T;
  name?: T;
  subHubs?: T;
  description?: T;
  categories?: T;
  layout?:
    | T
    | {
        recipeHero?: T | RecipeHeroBlockSelect<T>;
        singlePageHero?: T | SinglePageHeroBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        References?: T | ReferencesBlockSelect<T>;
        contentBlock?: T | ContentBlockSelect1<T>;
        tabbedContent?: T | TabbedContentBlockSelect<T>;
        author?: T | AuthorBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecipeHeroBlock_select".
 */
export interface RecipeHeroBlockSelect<T extends boolean = true> {
  containerSize?: T;
  image?: T;
  heading?: T;
  whoIsThisFor?:
    | T
    | {
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock_select".
 */
export interface TabbedContentBlockSelect<T extends boolean = true> {
  containerSize?: T;
  backgroundColor?: T;
  inactiveTabColor?: T;
  borderColor?: T;
  tabs?:
    | T
    | {
        title?: T;
        enableScale?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "howTo_select".
 */
export interface HowToSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  layout?:
    | T
    | {
        singlePageHero?: T | SinglePageHeroBlockSelect<T>;
        howToSections?:
          | T
          | {
              containerSize?: T;
              resources?:
                | T
                | {
                    image?: T;
                    title?: T;
                    linkType?: T;
                    url?: T;
                    file?: T;
                    id?: T;
                  };
              steps?:
                | T
                | {
                    heading?: T;
                    swapColumns?: T;
                    image?: T;
                    mobile_image?: T;
                    columnsProportion?: T;
                    tipMaxWidthPx?: T;
                    useContentRepeater?: T;
                    richText?: T;
                    contentRows?:
                      | T
                      | {
                          title?: T;
                          paragraph?: T;
                          id?: T;
                        };
                    tooltipEnabled?: T;
                    tooltipVariant?: T;
                    tooltipText?: T;
                    useListIndentation?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howToInformation?:
          | T
          | {
              containerSize?: T;
              heading?: T;
              list?: T;
              disclosure?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health_select".
 */
export interface HealthSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  subHubs?: T;
  layout?:
    | T
    | {
        singlePageHero?: T | SinglePageHeroBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        healthSections?: T | HealthSectionsBlockSelect<T>;
        contentBlock?: T | ContentBlockSelect1<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HealthSectionsBlock_select".
 */
export interface HealthSectionsBlockSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        type?: T;
        heading?: T;
        anchor?: T;
        tableOverflow?: T;
        tableIntro?: T;
        columns?:
          | T
          | {
              title?: T;
              columnType?: T;
              inputType?: T;
              id?: T;
            };
        tableRows?:
          | T
          | {
              cells?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        topContent?: T;
        enableImportant?: T;
        importantTitle?: T;
        importantText?: T;
        contentRows?:
          | T
          | {
              leftHeading?: T;
              rightText?: T;
              id?: T;
            };
        bottomContent?: T;
        content?: T;
        accordionIntro?: T;
        items?:
          | T
          | {
              title?: T;
              subtitle?: T;
              icon?: T;
              content?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subHubs_select".
 */
export interface SubHubsSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  collection?: T;
  publishedAt?: T;
  hub?: T;
  layout?:
    | T
    | {
        singlePageHero?: T | SinglePageHeroBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        healthSections?: T | HealthSectionsBlockSelect<T>;
        contentBlock?: T | ContentBlockSelect1<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubs_select".
 */
export interface HubsSelect<T extends boolean = true> {
  locked?: T;
  title?: T;
  subHubs?: T;
  layout?:
    | T
    | {
        hubHero?: T | HubHeroBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        contentBlock?: T | ContentBlockSelect1<T>;
        iconSlider?: T | IconSliderBlockSelect<T>;
        slider?: T | SliderBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        featuredWorkshop?: T | FeaturedWorkshopBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubHeroBlock_select".
 */
export interface HubHeroBlockSelect<T extends boolean = true> {
  containerSize?: T;
  backgroundColor?: T;
  heading?: T;
  subheading?: T;
  searchPlaceholder?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconSliderBlock_select".
 */
export interface IconSliderBlockSelect<T extends boolean = true> {
  title?: T;
  title_mobile?: T;
  boxes?:
    | T
    | {
        icon?: T;
        title?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlock_select".
 */
export interface SliderBlockSelect<T extends boolean = true> {
  containerSize?: T;
  title?: T;
  aspectRatio?: T;
  centerSlidesOnMobile?: T;
  overflowSetting?: T;
  desktopSlidesPerView?: T;
  items?:
    | T
    | {
        reference?: T;
        id?: T;
      };
  usePlaceholders?: T;
  placeholderImage?: T;
  placeholderTitle?: T;
  placeholderCount?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  containerSize?: T;
  content?: T;
  author?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedWorkshopBlock_select".
 */
export interface FeaturedWorkshopBlockSelect<T extends boolean = true> {
  label?: T;
  containerSize?: T;
  workshop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  locked?: T;
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  showDividers?: boolean | null;
  showSearch?: boolean | null;
  showAccount?: boolean | null;
  showLocation?: boolean | null;
  /**
   * Image shown in the header as the logo
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Optional icon shown before the label
         */
        icon?: ('home' | 'health_cross' | 'nutrition' | 'square-play' | 'utensils' | 'plus' | 'squareStack') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Image shown in the footer as the logo
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup".
 */
export interface Popup {
  id: number;
  enabled?: boolean | null;
  dismissible?: boolean | null;
  title?: string | null;
  colored_title_part?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pricing cards.
   */
  plans?:
    | {
        name: string;
        price: string;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  overlayColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  showDividers?: T;
  showSearch?: T;
  showAccount?: T;
  showLocation?: T;
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup_select".
 */
export interface PopupSelect<T extends boolean = true> {
  enabled?: T;
  dismissible?: T;
  title?: T;
  colored_title_part?: T;
  content?: T;
  plans?:
    | T
    | {
        name?: T;
        price?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaUrl?: T;
        id?: T;
      };
  overlayColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'workshops';
          value: number | Workshop;
        } | null)
      | ({
          relationTo: 'food';
          value: number | Food;
        } | null)
      | ({
          relationTo: 'recipes';
          value: number | Recipe;
        } | null)
      | ({
          relationTo: 'howTo';
          value: number | HowTo;
        } | null)
      | ({
          relationTo: 'health';
          value: number | Health;
        } | null)
      | ({
          relationTo: 'subHubs';
          value: number | SubHub;
        } | null)
      | ({
          relationTo: 'hubs';
          value: number | Hub;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}